### PR TITLE
Fix colinear check, add clipping algorithm, implement paralellism

### PR DESCRIPTION
**Pull request by VladGribinchuk**
This is an example of GOOD pull request.
First, describe changes in description. Don't hesitate to put images for better understanding.

This PR provides:
- fixes for inflating method
- clipping corner algorithm
- refactoring of the code for clarity and readability
- improving by openMP paralellism
image

### CODE REVIEW

**Comment by IlliaHryshchuk** [comment]
It looks understandable and readable

**Review by IlliaHryshchuk — APPROVED** [review]

**Comment by okrdima** [comment]
Thanks for good example PR.I saw how  inflating method could be improved  and additionally use open MP.In the future I will try to do such PR with a detailed description and result.I will also use the comments in the code to describe the operation of the complex method

**Review by okrdima — APPROVED** [review]

**Comment by 1m8o5s** [comment]
I try to use this example in my pull request

**Review by 1m8o5s — APPROVED** [review]

**Comment by VladGribinchuk** [comment]
Hope this example will help you, guys

**Pull request merged**
